config/routes.rb
Rails.application.routes.draw do
  
  get '/bet_set/index'
  get '/bet_set/email/:date/:type', :to => "bet_set#email"
  get '/bet_set/bet', :to => "bet_set#bet"
  post '/bet_set/submit', :to => "bet_set#submit"

  resources :teams

  resources :matches

  resources :players

  root :to => "bet_set#result"
end

app/models/player.rb
class Player < ActiveRecord::Base
  
  attr_accessible :name, :email, :total_penalty_kicks, :total_characters
  
  has_many :bets
  
  def result
    result = {
      matches: 0,
      scores: 0,
      characters: self.total_characters,
      penalties: self.total_penalty_kicks
    }
    self.bets.each do |bet|
      result[:matches] += bet.match.point if bet.winner.eql? bet.match.result
      result[:scores] += bet.match.point if bet.total_score.eql? bet.match.total_score
    end
    result
  end
    
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.uuid = SecureRandom.uuid

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params[:player]
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Name</label>
	</div>
	<div class="large-9 columns">
	  <%= f.text_field :name %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">E-mail</label>
	</div>
	<div class="large-9 columns">
	  <%= f.text_field :email %>
	</div>
  </div>
  <div class="row">
	<div class="large-6 large-centered columns">
      <%= f.submit :class => "button radius round" %>
	  <%= link_to 'Cancel', players_path, :class => "button radius round alert right" %>
	</div>
  </div>
  
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

app/views/players/index.html.erb
<h1>Players</h1>

<table>
  <thead>
    <tr>
	  <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
		<td><%= player.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>