config/routes.rb
Rails.application.routes.draw do
  
  get '/bet_set/index'
  get '/bet_set/email/:date/:type', :to => "bet_set#email"
  get '/bet_set/bet', :to => "bet_set#bet"
  post '/bet_set/submit', :to => "bet_set#submit"

  resources :teams

  resources :matches

  resources :players

  root :to => "bet_set#result"
end

app/models/match.rb
class Match < ActiveRecord::Base
  
  attr_accessible :location, :date_time, :team_a_id, :team_b_id, :allow_tie, :result, :penalty_kicks, :total_score, :stage, :point
  
  STAGES = [
    "Group Stage",
    "Round of 16",
    "Quarterfinals",
    "Semi-Finals",
    "Third-Place Play-Off",
    "Final"
  ]
  
  WINNERS_FOR_SELECT = [
    [ "Team A", 1 ],
    [ "Team B", 2 ],
    [ "TIE", 0 ]
  ]
  
  def team_a
    Team.find(team_a_id) rescue nil
  end
  
  def team_b
    Team.find(team_b_id) rescue nil
  end
  
  def winner_name
    case result
      when 0
        "TIE"
      when 1
        team_a.name
      when 2
        team_b.name
      else
        nil
      end
  end
  
  def est_time
    date_time.in_time_zone("Eastern Time (US & Canada)") rescue nil
  end
  
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
    @players = Player.all
    @bets = Hash.new
    Bet.all.each do |bet|
      @bets[bet.match_id.to_s] ||= Hash.new
      case bet.winner
        when 0
          winner = "TIE"
        when 1
          winner = bet.match.team_a.name
        when 2
          winner = bet.match.team_b.name
        else
          winner = nil
      end
      @bets[bet.match_id.to_s][bet.player_id.to_s] = {
        winner: winner,
        total_score: bet.total_score
      }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @match.uuid = SecureRandom.uuid

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params[:match]
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Stage</label>
	</div>
	<div class="large-9 columns">
	  <%= f.select :stage, Match::STAGES %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Allow Tie?</label>
	</div>
	<div class="large-9 columns">
	  <%= f.check_box :allow_tie %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Point</label>
	</div>
	<div class="large-9 columns">
	  <%= f.text_field :point %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Date Time</label>
	</div>
	<div class="large-9 columns">
	  <%= f.datetime_select :date_time %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Team A</label>
	</div>
	<div class="large-9 columns">
	  <%= f.collection_select :team_a_id, Team.all, :id, :name, prompt: true %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Team B</label>
	</div>
	<div class="large-9 columns">
	  <%= f.collection_select :team_b_id, Team.all, :id, :name, prompt: true %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Winner</label>
	</div>
	<div class="large-9 columns">
	  <%= f.select :result, Match::WINNERS_FOR_SELECT, prompt: true %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Penalty Kicks</label>
	</div>
	<div class="large-9 columns">
	  <%= f.number_field :penalty_kicks %>
	</div>
  </div>
  <div class="row">
	<div class="large-3 columns">
	  <label class="right inline">Total Score</label>
	</div>
	<div class="large-9 columns">
	  <%= f.number_field :total_score %>
	</div>
  </div>
  <div class="row">
	<div class="large-6 large-centered columns">
      <%= f.submit :class => "button radius round" %>
	  <%= link_to 'Cancel', matches_path, :class => "button radius round alert right" %>
	</div>
  </div>

<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

app/views/matches/index.html.erb
<h1>Matches</h1>

<table>
  <thead>
    <tr>
	  <th>Date Time</th>
	  <th>Teams</th>
	  <% @players.each do |player| %>
	  <th colspan="2"><%= player.name %></th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @matches.order(:date_time).each do |match| %>
      <tr>
		<td><%= link_to match.est_time.strftime("%b %-d @ %-H"), edit_match_path(match) %></td>
		<td><b><%= match.team_a.name rescue nil %></b> vs <b><%= match.team_b.name rescue nil %></b></td>
		<% @players.each do |player| %>
		<td<% if @bets[match.id.to_s].present? and @bets[match.id.to_s][player.id.to_s].present? and @bets[match.id.to_s][player.id.to_s][:winner].eql? match.winner_name %> class="selected"<% end %>>
			<%= @bets[match.id.to_s][player.id.to_s][:winner] if match.result.present? rescue nil %>
		</td>
		<td<% if @bets[match.id.to_s].present? and @bets[match.id.to_s][player.id.to_s].present? and @bets[match.id.to_s][player.id.to_s][:total_score].eql? match.total_score %> class="selected"<% end %>>
			<%= @bets[match.id.to_s][player.id.to_s][:total_score] if match.result.present? rescue nil %>
		</td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>